/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hedu.groovy.scripts.portlet.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the GroovyScript service. Represents a row in the &quot;GROOVY_SCRIPTS_GroovyScript&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hedu.groovy.scripts.portlet.model.impl.GroovyScriptModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hedu.groovy.scripts.portlet.model.impl.GroovyScriptImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GroovyScript
 * @see com.hedu.groovy.scripts.portlet.model.impl.GroovyScriptImpl
 * @see com.hedu.groovy.scripts.portlet.model.impl.GroovyScriptModelImpl
 * @generated
 */
@ProviderType
public interface GroovyScriptModel extends BaseModel<GroovyScript> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a groovy script model instance should use the {@link GroovyScript} interface instead.
	 */

	/**
	 * Returns the primary key of this groovy script.
	 *
	 * @return the primary key of this groovy script
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this groovy script.
	 *
	 * @param primaryKey the primary key of this groovy script
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this groovy script.
	 *
	 * @return the uuid of this groovy script
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this groovy script.
	 *
	 * @param uuid the uuid of this groovy script
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the groovy script ID of this groovy script.
	 *
	 * @return the groovy script ID of this groovy script
	 */
	public long getGroovyScriptId();

	/**
	 * Sets the groovy script ID of this groovy script.
	 *
	 * @param groovyScriptId the groovy script ID of this groovy script
	 */
	public void setGroovyScriptId(long groovyScriptId);

	/**
	 * Returns the script ID of this groovy script.
	 *
	 * @return the script ID of this groovy script
	 */
	public long getScriptId();

	/**
	 * Sets the script ID of this groovy script.
	 *
	 * @param scriptId the script ID of this groovy script
	 */
	public void setScriptId(long scriptId);

	/**
	 * Returns the user ID of this groovy script.
	 *
	 * @return the user ID of this groovy script
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this groovy script.
	 *
	 * @param userId the user ID of this groovy script
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this groovy script.
	 *
	 * @return the user uuid of this groovy script
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this groovy script.
	 *
	 * @param userUuid the user uuid of this groovy script
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this groovy script.
	 *
	 * @return the create date of this groovy script
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this groovy script.
	 *
	 * @param createDate the create date of this groovy script
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this groovy script.
	 *
	 * @return the modified date of this groovy script
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this groovy script.
	 *
	 * @param modifiedDate the modified date of this groovy script
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this groovy script.
	 *
	 * @return the title of this groovy script
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this groovy script.
	 *
	 * @param title the title of this groovy script
	 */
	public void setTitle(String title);

	/**
	 * Returns the content of this groovy script.
	 *
	 * @return the content of this groovy script
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this groovy script.
	 *
	 * @param content the content of this groovy script
	 */
	public void setContent(String content);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(GroovyScript groovyScript);

	@Override
	public int hashCode();

	@Override
	public CacheModel<GroovyScript> toCacheModel();

	@Override
	public GroovyScript toEscapedModel();

	@Override
	public GroovyScript toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}